CREATE TABLE twitter_comments(
id BIGINT PRIMARY KEY IDENTITY(1,1),
content VARCHAR(500) NOT NULL,
user_id BIGINT,
post_id BIGINT,
FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE ON UPDATE CASCADE
)